### PR TITLE
Support fissile build packages from final BOSH release

### PR DESCRIPTION
**Pull request by zhanggbj**
Currently there is a docker container to create BOSH `dev` release before `fissile build packages`. However there are lots of BOSH `final` release available in bosh.io which can be used directly. We drafted some code changes to support building packages from final release, so we can skip the `create-release` step and remove submodules, What do you think? Thanks.

Signed-off-by: Xuexiang Cui <cuixuex@cn.ibm.com>

Here are the details.
1. Added a check for final release structure when loading releases.
2. Added a NewFinalRelease.
3. Updated model/jobs,packages,release for loading packages and added UT.
4. Added a final release for UT.

### CODE REVIEW

**Comment by zhanggbj** [comment]
Hi,
I passed `go fmt` for the code changes locally, but it keeps failing in `ci` and I don't have authentication to see the result.

**Comment by aarondl** [comment]
```==> Formatting 
diff -u /tmp/build/78598764/src/github.com/SUSE/fissile/model/final_release.go.orig /tmp/build/78598764/src/github.com/SUSE/fissile/model/final_release.go
--- /tmp/build/78598764/src/github.com/SUSE/fissile/model/final_release.go.orig	2017-10-27 08:45:44.985321932 +0000
+++ /tmp/build/78598764/src/github.com/SUSE/fissile/model/final_release.go	2017-10-27 08:45:44.985321932 +0000
@@ -2,9 +2,10 @@
 
 import (
 	"fmt"
-	"gopkg.in/yaml.v2"
 	"io/ioutil"
 	"path/filepath"
+
+	"gopkg.in/yaml.v2"
 )
 
 // NewFinalRelease will create an instance of a BOSH final release
Makefile:15: recipe for target 'format' failed
make: *** [format] Error 1
make: Leaving directory '/tmp/build/78598764/src/github.com/SUSE/fissile'```

yamlv2 is an external package, despite it called the `fmt` check we use `goimports` to format the source code in CI. `goimports` also rearranges imports to make them a little more sane so this is the problem you're running into. If you use the same tool to format the code it should fix it up.

As for the actual changes, we'll get someone to code review them soon :)

**Comment by zhanggbj** [comment]
@aarondl, thank you for the information, all checks have passed this time:) And looking forward to the review result. Thanks!

**Comment by viovanov** [comment]
@zhanggbj this lgtm 
Does the release need to be unpacked before using it with fissile?
What releases have you tested with? (other than the assets you added for the test)

**Comment by zhanggbj** [comment]
Hi @viovanov 
Yes, to use a final release, we need to extract it into the release path `src/{release-name}/` and it should have at least files/dir as below(normally a BOSH final release contains all of these files).
```
src
├──<release_name>
│   ├── LICENSE
│   ├── jobs
│   ├── packages
│   └── release.MF
```
I also tested with a [BOSH final release](https://bosh.io/releases/github.com/cloudfoundry/bosh?all=1) and [a dev release](https://github.com/cloudfoundry/bosh-softlayer-cpi-release) and deployed a director on k8s successfully. Thanks!

**Comment by viovanov** [comment]
@zhanggbj thanks, I'm testing this right now.
If all goes well, I'll merge as soon as I'm done.

**Comment by viovanov** [comment]
@zhanggbj I've tested that I could create images from final BOSH releases and dev releases still work fine.
Can you please take care of the earlier comment so we can merge this? thnx

**Comment by zhanggbj** [comment]
@viovanov 
Thank you for your review.
I've addressed all of the comments. Since it was mixed after rebasing with master, would you please help take another review here PR #297 ? Thanks!

**Comment by viovanov** [comment]
closed in favor of #297

**Pull request closed without merging**
